dependencies:
  rag_converter.plugins.builtin.doc_to_docx:
  - libreoffice
  rag_converter.plugins.builtin.svg_to_png:
  - inkscape
  rag_converter.plugins.builtin.gif_to_mp4:
  - ffmpeg
  rag_converter.plugins.builtin.webp_to_png:
  - ffmpeg
  rag_converter.plugins.builtin.audio_to_mp3:
  - ffmpeg
  rag_converter.plugins.builtin.video_to_mp4:
  - ffmpeg
