modules:
  - rag_converter.plugins.builtin.doc_to_docx
  - rag_converter.plugins.builtin.doc_to_pdf
  - rag_converter.plugins.builtin.docx_to_pdf
  - rag_converter.plugins.builtin.ppt_to_pdf
  - rag_converter.plugins.builtin.html_to_pdf
  - rag_converter.plugins.builtin.html_to_md
  - rag_converter.plugins.builtin.text_to_md
  - rag_converter.plugins.builtin.xlsx_to_pdf
  - rag_converter.plugins.builtin.xlsx_to_md
  - rag_converter.plugins.builtin.svg_to_png
  - rag_converter.plugins.builtin.gif_to_mp4
  - rag_converter.plugins.builtin.webp_to_png
  - rag_converter.plugins.builtin.audio_to_mp3
  - rag_converter.plugins.builtin.video_to_mp4
