modules:
  - rag_converter.plugins.builtin.doc_to_docx
  - rag_converter.plugins.builtin.svg_to_png
  - rag_converter.plugins.builtin.gif_to_mp4
  - rag_converter.plugins.builtin.webp_to_png
  - rag_converter.plugins.builtin.audio_to_mp3
  - rag_converter.plugins.builtin.video_to_mp4
